### ISSUE TITLE
When "config-infra-prod.yml" file is changed, 3 pipelines are automatically triggered and failed. 

### ISSUE THREAD

**Issue by yelizkilinc** [Azure/mlops-v2#109]
### Describe the bug or the issue that you are facing

In Outer loop first step, when "config-infra-prod.yml" or dev yaml files are changed, 3 pipelines (deploy-online-endpoint-pipeline, batch endpoint and training pipelines  are automatically triggered on Azure DevOps and failed. They should not have run.

### Steps/Code to Reproduce

1.In Outer loop first step, change "config-infra-prod.yml" or dev yaml files
2. Check Azure Devops pipelines

### Expected Output

They should not have triggered

### Versions

-

### Which platform are you using for deploying your infrastrucutre?

Azure DevOps (ADO)

### What are you using for deploying your infrastrucutre?

Bicep

### Are you using Azure ML CLI v2 or Azure ML Python SDK v2

Azure ML Python SDK v2

### Describe the example that you are trying to run?

testing classical project type

**Comment by sdonohoo** [comment]
This issue is fixed in PR https://github.com/Azure/mlops-project-template/pull/131 awaiting review

**Comment by setuc** [comment]
Resolved
