### ISSUE TITLE
 Repository mlops-templates references endpoint github-connection which does not exist or is not authorized for use

### ISSUE THREAD

**Issue by kunanba** [Azure/mlops-v2#113]
### Describe the bug or the issue that you are facing

Cannot create pipeline to train model (/mlops/devops-pipelines/deploy-model-training-pipeline.yml) with this error:  Repository mlops-templates references endpoint github-connection which does not exist or is not authorized for use
Are there any instructions missing with regards to defining pipeline resource?

### Steps/Code to Reproduce

All steps up to **Deploy Azure Machine Learning Model Training Pipeline** step
![image](https://github.com/Azure/mlops-v2/assets/51249060/d3bd9587-4488-45e1-ae23-73825bd7a0b0)

### Expected Output

Pipeline is expected to run and complete

### Versions

Azure DevOps.
I changed branches to main.
Bicep
Azure ML CLI 2
Classical ML example

### Which platform are you using for deploying your infrastrucutre?

Azure DevOps (ADO)

### What are you using for deploying your infrastrucutre?

Bicep

### Are you using Azure ML CLI v2 or Azure ML Python SDK v2

Azure ML CLI v2

### Describe the example that you are trying to run?

Classical ML

**Comment by setuc** [comment]
@kunanba Can you check the following in your code
1. Check if the pipeline is referring to the dev or prod configurations. We have [the two lines ](https://github.com/setuc/mlops-project-template/blob/ad5aa9ecc0201d0609151c204ea105b21323236c/config-infra-dev.yml#L17-L18) where you set the name of the service connection that you have set. I believe that you have set this to github-connection. 
2. Do check if you have setup the Service Connection to Azure and ensure that you have set it to github-connection. Both these names have to match. See [Step 4 ](https://github.com/setuc/mlops-project-template/blob/ad5aa9ecc0201d0609151c204ea105b21323236c/config-infra-dev.yml#L17-L18) in the Setup MLOps Example.

**Comment by kunanba** [comment]
Hi Setu,
Thank you for your quick response.
1. It is set to prod in mlops-project-templates:
![image](https://github.com/Azure/mlops-v2/assets/51249060/4f69a1b1-0078-4dad-96ca-3b948246be2e)
It is supposed to use prod config if the branch is main in taxi-regression, correct?
![image](https://github.com/Azure/mlops-v2/assets/51249060/0dfbb6dd-a620-4851-8397-7009f11b8cf5)
2. I'm not sure which step you're referring to as it takes me to the same config-file with two highlighted lines. If this is the referenced step **Create Service Connections** I'm not sure where to set github-connection.
Please advise.

**Comment by kunanba** [comment]
When I create new model-training-pipeline, resources in the yaml file are listed as follows:
![image](https://github.com/Azure/mlops-v2/assets/51249060/bfe29382-bfeb-46ab-9dd9-8b04cb21fede)
Highlighted line mentions that github-connection needs to be set up and hardcoded. Is this ignored when one is deploying with Azure DevOps?

**Comment by delbert** [comment]
to clarify, this resource definition worked for me in the ADO + Classic ML case:

```
resources:
  repositories:
    - repository: mlops-templates  # Template Repo
      name: mlops-templates # need to change org name from "Azure" to your own org
      type: git
      ref: main
```
