### ISSUE TITLE
For free/VS MCT subscriptions vcore quota limit of 6 in eastus causes endpoint deployment failure

### ISSUE THREAD

**Issue by strugdt** [Azure/mlops-v2#124]
### Describe the bug or the issue that you are facing

Please can we also consider changing the VM type for compute, and I see for a Trial/Free Subscription/Visual Studio MCT Subscriptions, in the region selected 'éastus' a quota limit of 6 vcore applies. As a result all subsequent provisioning for say compute for batch interencing will fail for all using trial subscription. Perhaps would be nice to put a note before deploying endpoints exercise, that there is need to adjust either region, or vm type to suceed. 

![image](https://github.com/Azure/mlops-v2/assets/16652407/a779afae-1450-4f9d-bf63-008c35164a97)

	Code: InferencingClientCreateDeploymentFailed
	Message: InferencingClient HttpRequest error, error detail: {"errors":{"VmSize":["Not enough quota available for Standard_DS3_v2 in SubscriptionId fe0c79f9-9d6e-43fc-8d3f-d9e79d40ea49. Current usage/limit: 0/6. Additional needed: 8 Please see troubleshooting guide, available here: [https://aka.ms/oe-tsg#error-outofquota"]}

![image](https://github.com/Azure/mlops-v2/assets/16652407/cbfd3a8e-eb07-4e07-af5c-89ff8ee2060e)

Thanks a lot!

### Steps/Code to Reproduce

For free subscriptions, limit of 6 vcores for the given vm type in eastus region fails due to not enough vcore available to further provision compute for endpoint deployment. 

### Expected Output

We can perhaps add a note for users to either change region, and vm type upfront at the beginning as per their available quota in the ADO pipelines. I believe up to 20 vcore for many other regions and vm type would suffice. 

### Versions

ADO

### Which platform are you using for deploying your infrastrucutre?

Azure DevOps (ADO)

### What are you using for deploying your infrastrucutre?

Bicep

### Are you using Azure ML CLI v2 or Azure ML Python SDK v2

Azure ML CLI v2

### Describe the example that you are trying to run?

Tabular/Classic

**Comment by setuc** [comment]
Disussing in #123

**Comment by setuc** [comment]
Added a note in the documentation and merged the PR https://github.com/Azure/mlops-v2/pull/125
