### ISSUE TITLE
[repo] SSH auth shouldn't be needed for git cloning

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/mlops-v2#25]
## Why?

This is an annoying extra step. If I can `gh repo clone` the private repo, I shouldn't need to do this.

## How?

Can the scripts be modified to use the `gh` CLI? Some other solution?

**Comment by lostmygithubaccount** [comment]
wasn't too bad using this: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account, perhaps document/provide optional script to setup all this

**Comment by ManojBableshwar** [comment]
agree with Cody here... most folks have clone setup anyways.
