### ISSUE TITLE
How to achieve Continuous Integration

### ISSUE THREAD

**Issue by MurugeswariMuthurajan** [Azure/mlops-v2#36]
Hi,

As per the process, we are training the and registering the model in DEV Workspace. But how to bring/ deploy that model in Stage.

It would be better if we have the steps between registering the model in dev workspace and deploy in  Stage Workspace

**Comment by setuc** [comment]
Hi @MurugeswariMuthurajan 
Are you referring to the moving the models across different workspaces?

**Comment by MurugeswariMuthurajan** [comment]
Hi @setuc 

Yes, Regarding moving the models across workspaces

Currently we have achieved that using release pipeline in Azure Devops [ Steps In Release Pipeline : Downloaded the model from dev, registered in test and deployed in test]

But we need to confirm whether it is a right approach or have to do something with training pipeline

Thanks

**Comment by setuc** [comment]
Yes. The approach that you have taken is absolutely correct. You can use download/upload/register the model for now. 

As Azure ML evolves, we will continue to update the approaches. So keep a watch out for new updates. 

Setu

**Comment by MurugeswariMuthurajan** [comment]
> Yes. The approach that you have taken is absolutely correct. You can use download/upload/register the model for now.
> 
> As Azure ML evolves, we will continue to update the approaches. So keep a watch out for new updates.
> 
> Setu
