### ISSUE TITLE
issues with mlops-v2/sparse_checkout.sh

### ISSUE THREAD

**Issue by ManojBableshwar** [Azure/mlops-v2#38]
I bumped into the following issues while running mlops-v2/sparse_checkout.sh. I worked around them because i knew what the cmds were trying to accomplish.

Issue 1:
+ git clone --depth 1 --filter=blob:none --sparse https://github.com/azure/mlops-project-template MLOps711Demo
Cloning into 'MLOps711-sparse'...
fatal: cannot change to 'https://github.com/azure/mlops-project-template': No such file or directory
error: failed to initialize sparse-checkout

workaroud - used this cmd (not sure why above doesn't work)
git clone https://github.com/azure/mlops-project-template  --depth 1 --filter=blob:none  MLOps711Demo

Issue 2:
+ git init -b main
error: unknown switch `b'
usage: git init [-q | --quiet] [--bare] [--template=<template-directory>] [--shared[=<permissions>]] [<directory>]

    --template <template-directory>
                          directory from which templates will be used
    --bare                create a bare repository
    --shared[=<permissions>]
                          specify that the git repository is to be shared amongst several users
    -q, --quiet           be quiet
    --separate-git-dir <gitdir>
                          separate git dir from working tree

Workaound: first inited the repo and then renamed branch from master to main

git init
git add . && git commit -m 'initial commit'
git branch -m master main

**Comment by socullen** [comment]
Thank you very much!
I was facing the same issues and this workaround helped solve them.

**Comment by krisbock** [comment]
This is also caused by having git version 2.25.1.  Upgrading to git version 2.37.3 resolves this.  Workarounds not required.
