### ISSUE TITLE
How to stop the instance in online deployment when not required

### ISSUE THREAD

**Issue by MurugeswariMuthurajan** [Azure/mlops-v2#48]
Hi,

In online-deployment config file, we are mentioning the instance type and instance count

![image](https://user-images.githubusercontent.com/107349920/183386359-2f3bbe08-3cdc-4ecd-8b4c-83e478c033dc.png)

But where the instance is actually created?  We tried to locate in compute session of ml workspace but could not find it

And the minimum value of instance count is 1 [ Tried making it 0 and enabled scale settings but we are getting the error]. So the instance is always running which is incurring us the additional cost when not in use

So please suggest a way to stop the instance/ additional cost when not using

Thanks,
M.Murugeswari

**Comment by setuc** [comment]
Hi,
 The online endpoint cannot be stopped. You need to have at least one machine running. Having said that, you may want to consider batch endpoints if your needs are sporadic. In that the batch endpoint cluster will only start when its needed. 

References: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-use-batch-endpoint
Classical Tabular Batch Endpoint: https://github.com/Azure/mlops-project-template/blob/main/classical/aml-cli-v2/mlops/devops-pipelines/deploy-batch-endpoint-pipeline.yml
