### ISSUE TITLE
GitHub Actions instead of DevOps

### ISSUE THREAD

**Issue by michalmar** [Azure/mlops-v2#51]
Do you have guide (similar to Quickstart) on how to do everything in GitHub rather than Azure DevOps - probably only the orchestration part is in Azure DevOps currently.

Moreover, currently referencing GitHub repos in Azure DevOps pipeline is considered as unsafe:
![image](https://user-images.githubusercontent.com/16072588/185957398-9eca4d5b-0f68-4f37-8de2-a031e71efada.png)

@msteller-Ai

**Comment by setuc** [comment]
@michalmar  We have just released Github Actions and you can find them in [quick start guide ](https://github.com/Azure/mlops-v2/blob/main/QUICKSTART.md). The outer loop deploys with that. This is currently supported for Classical/ Tabular datasets via both sdk and cli v2. You can also do it with cli for computer vision tasks. 

We plan to add the missing patterns for NLP and CV in the upcoming release.

**Comment by cindyweng** [comment]
IaC is not yet available for Github Actions. Will be in the next release
