### ISSUE TITLE
Model tagging as Legacy

### ISSUE THREAD

**Issue by MuMu2807** [Azure/mlops-v2#56]
Hi,

The model which has been trained and registered is now showing as Legacy

![image](https://user-images.githubusercontent.com/112151473/188666074-a7741db5-c3e7-4a93-81aa-3e5980377ab8.png)

We tried creating few new automl models. But those models were also created with the tag Legacy 

Can you please let us know on what basis the model is getting tagged as legacy

Thanks

**Comment by cindyweng** [comment]
this is something happening in the backend of AML, but now should be fixed
