### ISSUE TITLE
Enterprise readiness where Github is not the source control repository

### ISSUE THREAD

**Issue by drosevear** [Azure/mlops-v2#59]
The current Quickstart doesn't cater for organisations that don't use GitHub as their source control repository. There's a need for these organisations to get started on Azure quickly – for MLOps projects to be initialised in Azure DevOps itself based on 'MLOps version' and 'project type'.

**Comment by setuc** [comment]
@drosevear There is nothing in the guide that prevents you from using Azure DevOps as your source control repository. We have deployed this repository with organizations that had private GitLab with no changes. 

Are you requesting that we add additional documentation and/or step by step guides for someone to work with Azure DevOps?

**Comment by setuc** [comment]
Thank you for your PR #54 . Let us review and add the documentation and merge the PR. I dont see any issue with the template.

**Comment by drosevear** [comment]
Thanks @setuc 😊 I'll add a readme in the .azuredevops directory?

**Comment by cindyweng** [comment]
has been merged! if you want to add a readme, would be awesome :) but else no worries
