### ISSUE TITLE
Correct Deployment of Dev Environments

### ISSUE THREAD

**Issue by andrewblance** [Azure/mlops-v2#65]
Hello,

Thank you for this repo, and all your hard work maintaining it. I am trying to deploy the quickstart guide - I have successfully been able to deploy the outer loop prod environment using Azure DevOps.

However, my understanding was that I would end up with a `rg-mlopsv2-XXXprod` and an `rg-mlopsv2-XXXdev` - an area to do the dev work on the project, and an area to host the production model (in the future, I want to expand to also contain a UAT env). The pipelines would allow me to move models between the two. However, after running the `tf-ado-deploy-infra.yml` pipeline I only have the prod environment. I tried creating a new branch, called dev, and reran the pipeline. However, now, during the `Terraform Init` step I get an error: 

`##[error]Error: There was an error when attempting to execute the process '/opt/hostedtoolcache/terraform/0.14.7/x64/terraform'. This may indicate the process failed to start. Error: spawn /opt/hostedtoolcache/terraform/0.14.7/x64/terraform ENOENT`

The guide always mentions staying on main, and doesn't mention creating a dev environment. Have I conceptually misunderstood what architecture (ie, there shouldn't be a `rg-mlopsv2-XXXdev`), or, if I need to create this env how do I overcome my error?

**Comment by andrewblance** [comment]
I believe I understand my issue: the `terraform_workingdir` within `config-infra-dev.yml` is pointing to the wrong place - the default option is `infrastructure/terraform`, it should just be `infrastructure`. Making this change allows the dev environments to deploy.

I now suppose this implies my original understanding of the system is correct - there is a dev env and a prod env, with pipelines to push between the two?

**Comment by cindyweng** [comment]
this is fixed as of 14 days ago :) thanks for alerting us
