### ISSUE TITLE
[Quickstart.md] Deploying Infrastructure via Azure DevOps

### ISSUE THREAD

**Issue by saiham6** [Azure/mlops-v2#72]
Hi, 
I am facing an issue with the deployment via Azure Pipeline. When I run the pipeline, the following error is thrown. 

![Screenshot_20221130_192350](https://user-images.githubusercontent.com/36539728/204891037-f486157d-6671-446f-8b07-4bc25b07ecb6.png)

It seemed like I had to change the resource repositories and connections. So, I tried changing it to the following and another error is thrown.

![Screenshot_20221130_192212](https://user-images.githubusercontent.com/36539728/204891291-31a541a3-64e5-48ec-963f-7f1d2f5ad1b6.png)

Can anyone help me with the issue? 

Thanks,
Saiham

**Comment by cindyweng** [comment]
you need the terraform extension (it's at the top of the quickstart)

**Comment by setuc** [comment]
I am assuming that this issue has been resolved succesfully.

**Comment by corticalstack** [comment]
@saiham6 Garteful for feedback on how you resolved as I have same (and have DevOps terraform extension installed). Thanks!
