### ISSUE TITLE
Model Promotion

### ISSUE THREAD

**Issue by levalencia** [Azure/mlops-v2#75]
I wasnt able to find in the code or in the documentation anything related to model promotion and data drift.

If I have a daily ingestion of new data and I run the training pipeline on a daily basis, probably at some point the daily model will have better metrics that the one deployed.

How can I replace the model ONLY if the metrics are better? Could you provide some guidance or links if it exists?

**Comment by setuc** [comment]
@levalencia One approach that we have is code based.  This will only register the model if the pre-defined metrics are better

https://github.com/Azure/mlops-project-template/blob/5801db4951eab35d0f443c952314d7de60c6da11/classical/aml-cli-v2/data-science/src/evaluate.py#L132

This is one such approach. 

As far as data drift goes, you can work with some development that a few of my colleagues had done:
https://github.com/Azure/data-model-drift
