### ISSUE TITLE
Has responsible Ai been discontinued in mlopsv2? 

### ISSUE THREAD

**Issue by lokierao** [Azure/mlops-v2#77]
Hi @setuc  In the previous code responsible AI related code was present. Now code is not present as well as  I am unable to find https://github.com/Azure/RAI-vNext-Preview github repo.

Thank you

**Comment by setuc** [comment]
You can find the responsible AI Toolbox here: https://github.com/microsoft/responsible-ai-toolbox

We are rearranging the repo a bit, but you can find the code of RAI as part of the pipeline here:
https://github.com/Azure/mlops-project-template/blob/05772448d6cfdabe143c0bf0cc33b5b93647af56/classical/rai-aml-cli-v2/mlops/azureml/train/pipeline.yml
