### ISSUE TITLE
Checkout mlops-project-template@cindy-test to s/mlops-project-template

### ISSUE THREAD

**Issue by levalencia** [Azure/mlops-v2#83]
### Describe the bug or the issue that you are facing

Is it correct to use a branch different to main?
Starting: Checkout mlops-project-template@cindy-test to s/mlops-project-template

### Steps/Code to Reproduce

Same as https://github.com/Azure/mlops-v2/blob/main/documentation/deployguides/deployguide_ado.md
Section: Set up source repository with Azure DevOps

### Expected Output

I dont have an error per see, but its weird to me that its using a named branch (cindy-test) instead of main.

### Versions

I am using: initialise-project.yml
from mlops-v2 repo

### Which platform are you using for deploying your infrastrucutre?

Azure DevOps (ADO)

### What are you using for deploying your infrastrucutre?

Pre-Deployed

### Are you using Azure ML CLI v2 or Azure ML Python SDK v2

Azure ML Python SDK v2

### Describe the example that you are trying to run?

I am just following the section: 
Setup MLOps V2 and a New MLOps Project in Azure DevOps

from:
https://github.com/Azure/mlops-v2/blob/main/documentation/deployguides/deployguide_ado.md

We use ADO not GHA

**Comment by levalencia** [comment]
looks like when I imported the repos, the default branches are not the main ones

**Comment by corticalstack** [comment]
Same for mlops-v2 repo here on next run, which shows branch feathr as default (and main as failed, with further beautifully named main_xxx branches)

![image](https://user-images.githubusercontent.com/3995321/226860372-11541ac2-5421-4341-bcdf-2f970eb3ced9.png)
