### ISSUE TITLE
Question: Computer Vision pattern availability?

### ISSUE THREAD

**Issue by tgokal** [Azure/mlops-v2#91]
Hi Team, 

What are the timelines for the computer vision pattern to be available in the inner loop component?

**Comment by setuc** [comment]
Hi,
 We already have a CV pattern now. See https://github.com/Azure/mlops-project-template/tree/main/cv

You can pick them when running the sparse checkout script. Change from classical to cv. 

https://github.com/Azure/mlops-v2/blob/a963d1f3904b6a843579be71134b4a30e6f8a804/sparse_checkout.sh#L2

We support Azure ML SDK v1 and Azure ML CLI v2.
